# ---------------------------------------------------------------------------
# CHECKPOINT A5 -- generated by tools/build_checkpoints.py. Do not edit here.
#
# Everything up to and including mission A5 is solved. Everything after it is
# still the starter stub, waiting for you.
#
# Read it before you run it. Adopting a checkpoint is only worth the milestone
# you skipped if you understand what it does.
# ---------------------------------------------------------------------------
"""Mission A5 (stretch): a consumer gated on data, not on a clock.

This is the payoff of A4's asset event. The DAG has no schedule of its own -- it
runs when `rootsmarkt_daily_revenue` is published, and A4 publishes that only
when the revenue figure passed the plausibility gate.

So the ordering guarantee is not "07:00 has happened". It is "a data product we
consider valid exists". That distinction is the whole of the Airflow half.

Airflow 3.3 supports this directly: `schedule=[asset]`, plus conditional forms
like `schedule=(asset_a & asset_b)`. Worth stating plainly in the debrief,
because "Airflow cannot do data-aware orchestration" is a claim participants will
have read somewhere and it is false for this version.
"""

from airflow.sdk import Asset, dag, task

# The asset is REDEFINED here rather than imported from rootsmarkt_delivery.
#
# Importing it looks tidier and is a trap: importing that module executes it,
# which registers `rootsmarkt_delivery` a second time while the DagBag is
# processing THIS file, and Airflow rejects the duplicate:
#
#   AirflowDagDuplicatedIdException: Ignoring DAG rootsmarkt_delivery from
#   dags/rootsmarkt_delivery.py - also found in dags/rootsmarkt_consumer.py
#
# Assets are identified by NAME, not by object identity, so two definitions
# agreeing on the name refer to the same asset. This is the normal way to
# reference another DAG's asset, and it is why producer and consumer need no
# code dependency on each other at all -- worth pointing out in the A5 debrief.
DAILY_REVENUE = Asset(
    name="rootsmarkt_daily_revenue",
    # NOT postgres:// -- providers register URI normalizers for their own
    # schemes, and the Postgres one (airflow/providers/postgres/assets/postgres.py)
    # demands exactly `postgres://host:port/database/schema/table`. Anything else
    # fails at DAG PARSE time:
    #
    #   ValueError: URI format postgres:// must contain database, schema and table names
    #
    # Conforming would also drag the team-specific schema into parse time, so a
    # missing or wrong env var would break DAG import for the whole room.
    # Normalizers are registered for file://, postgres:// and postgresql:// only,
    # so a project-owned scheme is stable and identical for every team.
    uri="rootsmarkt://warehouse/daily_revenue",
)


@dag(
    dag_id="rootsmarkt_finance_report",
    schedule=[DAILY_REVENUE],   # <- data-driven, not time-driven
    catchup=False,
    tags=["rootsmarkt", "solution", "stretch"],
    doc_md=__doc__,
)
def rootsmarkt_finance_report():

    @task
    def build_report(**context) -> dict:
        """Read what the producer told us about the asset it published.

        `triggering_asset_events` carries the metadata A4 attached, so the
        consumer knows the revenue total and the range it was judged against
        without re-querying anything.
        """
        events = context.get("triggering_asset_events") or {}
        summary = {}
        for asset, asset_events in events.items():
            for event in asset_events:
                summary[getattr(asset, "name", str(asset))] = dict(event.extra or {})

        print(f"Finance report built from asset events: {summary}")
        return summary

    build_report()


rootsmarkt_finance_report()
