# ---------------------------------------------------------------------------
# CHECKPOINT A4 -- generated by tools/build_checkpoints.py. Do not edit here.
#
# Everything up to and including mission A4 is solved. Everything after it is
# still the starter stub, waiting for you.
#
# Read it before you run it. Adopting a checkpoint is only worth the milestone
# you skipped if you understand what it does.
# ---------------------------------------------------------------------------
"""Rootsmarkt daily delivery pipeline — missions A1 to A4.

This is your file. You will be editing it for the whole Airflow block.

Read the briefs in `missions/` as you go: A1 first, then A2, A3, A4.

WHAT IS ALREADY DONE FOR YOU
    - The DAG exists and is registered. It parses right now; check the UI.
    - `ensure_warehouse_table` is written. It is the one piece of SQL the
      orchestrator owns, and it is idempotent so a re-run is harmless.
    - Every piece of DATA PROCESSING is written and sealed, in the
      `rootsmarkt_processing` package. You should never need to open it, but
      reading it is allowed and often the fastest way to find a signature.

WHAT YOU WILL WRITE
    Orchestration. Every TODO below is a decision about *when* something runs,
    *what counts as success*, and *what the system should record* -- not about
    how to parse a CSV.

THE LAYER SPLIT, WHICH IS THE POINT OF THE DAY
    Processing  = reading, cleaning, aggregating, loading.   Sealed package.
    Orchestration = sequencing, failure policy, retries,     THIS FILE.
                    what "done" means, what gets recorded.

    When you write a line here, you should be able to say which one it is. If
    you cannot, that line is probably in the wrong file.

STUCK?
    roots hint a2            # two hints per mission, self-service
    roots checkpoint a2      # adopt a known-good state and keep moving
"""

import os
from datetime import timedelta
from pathlib import Path

from airflow.sdk import Asset, dag, task
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator

from rootsmarkt_processing import clean, load, revenue, source, validate
from rootsmarkt_processing.config import (
    clean_file,
    require_delivery_file,
    delivery_file,
    team_config,
)

# Airflow 3 moved this to airflow.sdk.exceptions; the old path still works but
# warns on every parse. Try the current one first, and keep the fallbacks so a
# DAG parse error can never mask a real problem.
try:
    from airflow.sdk.exceptions import AirflowFailException
except ImportError:  # pragma: no cover
    try:
        from airflow.exceptions import AirflowFailException
    except ImportError:
        AirflowFailException = RuntimeError

# Data paths come from rootsmarkt_processing.config, anchored to wherever
# config/team.yaml lives -- which is the repo root on the host and
# /usr/local/airflow in this container. The Dockerfile sets
# ROOTSMARKT_DATA_DIR to a directory Astro actually mounts, so files written
# here are visible from the host.

# The sealed processing layer is BAKED INTO THE IMAGE (decision D-034), while
# dags/ is live-mounted. So editing packages/ and restarting is not enough --
# the container keeps the old copy, and the mismatch surfaces mid-run as a bare
# `AttributeError: module ... has no attribute ...` pointing at a DAG line that
# looks perfectly correct.
#
# Checking at import time turns that into a DAG import error, visible in the UI
# straight away and naming the remedy.
_REQUIRED = {
    "rootsmarkt_processing.load": ("dsn_from_airflow_conn", "load_daily_revenue"),
    "rootsmarkt_processing.source": ("client_from_airflow_conn",),
    "rootsmarkt_processing.config": ("require_delivery_file", "clean_file"),
}
for _module_name, _names in _REQUIRED.items():
    _module = __import__(_module_name, fromlist=["_"])
    _missing = [n for n in _names if not hasattr(_module, n)]
    if _missing:
        raise RuntimeError(
            f"{_module_name} is missing {', '.join(_missing)}. The image has a stale copy of "
            "the sealed processing layer -- packages/ is baked in at build time, so a restart "
            "is not enough. Rebuild with `astro dev start` (add --no-cache if it persists)."
        )


DW_CONN_ID = "rootsmarkt_dw"      # pre-provisioned; A3 is not a credentials exercise
SUPPLYHUB_CONN_ID = "supplyhub"   # created by participants -- that IS mission A1

# The data product, as something the rest of the platform can depend on.
# Airflow 3.3 has first-class assets; this is not a Dagster-only idea, and the
# course says so out loud (decision D-009).
DAILY_REVENUE = Asset(
    name="rootsmarkt_daily_revenue",
    # NOT postgres:// -- providers register URI normalizers for their own
    # schemes, and the Postgres one (airflow/providers/postgres/assets/postgres.py)
    # demands exactly `postgres://host:port/database/schema/table`. Anything else
    # fails at DAG PARSE time:
    #
    #   ValueError: URI format postgres:// must contain database, schema and table names
    #
    # Conforming would also drag the team-specific schema into parse time, so a
    # missing or wrong env var would break DAG import for the whole room.
    # Normalizers are registered for file://, postgres:// and postgresql:// only,
    # so a project-owned scheme is stable and identical for every team.
    uri="rootsmarkt://warehouse/daily_revenue",
)

DEFAULT_BUSINESS_DATE = os.environ.get("ROOTSMARKT_BUSINESS_DATE", "2026-03-02")


@dag(
    dag_id="rootsmarkt_delivery",
    schedule=None,  # triggered manually; scheduling is out of scope
    catchup=False,
    params={"business_date": DEFAULT_BUSINESS_DATE},
    default_args={"retries": 2, "retry_delay": timedelta(seconds=30)},
    tags=["rootsmarkt", "solution"],
    doc_md=__doc__,
)
def rootsmarkt_delivery():

    @task
    def fetch_delivery(**context) -> dict:
        """A1. Ask SupplyHub for a specific business date and land the file.

        Retries are inherited from default_args: an unreachable source is exactly
        the kind of transient failure worth retrying.
        """
        business_date = context["params"]["business_date"]
        cfg = team_config()
        client = source.client_from_airflow_conn(SUPPLYHUB_CONN_ID)

        meta = client.get_delivery(business_date)
        path = client.download(meta, delivery_file(meta.business_date))

        # Only small values go through XCom. The data itself went to disk.
        return {
            "requested_date": business_date,
            "received_date": meta.business_date,
            "delivery_id": meta.delivery_id,
            "row_count": meta.row_count,
            "checksum_sha256": meta.checksum_sha256,
            "path": str(path),
        }

    @task(retries=0)
    def assert_delivery_is_current(delivery: dict, **context) -> dict:
        """A2. The source answered 200. Did it answer the question we asked?

        retries=0 on purpose. SupplyHub serves the stale file deterministically,
        so retrying just fetches the same lie again -- the failure needs a human,
        not another attempt. Deciding that is orchestration reasoning, and it is
        the whole point of this task.
        """
        if delivery["received_date"] != delivery["requested_date"]:
            raise AirflowFailException(
                f"stale delivery: asked for {delivery['requested_date']}, "
                f"was served {delivery['received_date']} ({delivery['delivery_id']}, "
                f"{delivery['row_count']} rows) with HTTP 200. "
                "Retrying will return the same file."
            )
        return delivery

    @task
    def transform(delivery: dict, **context) -> dict:
        """A3. Delegate to the sealed processing layer, then hand off on disk."""
        business_date = delivery["received_date"]
        cfg = team_config()

        result = clean.clean_sales(delivery["path"], cfg.expected_stores)

        # Stores outside our roster are dropped here. SupplyHub's test store is
        # real data in the file, so no type check removes it -- deciding it is
        # not Rootsmarkt revenue is a business rule we own.
        expected = set(cfg.expected_stores)
        result.rows = [r for r in result.rows if r["store_id"] in expected]

        out = clean_file(business_date)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", encoding="utf-8") as fh:
            fh.write("store_id,sale_date,product_id,category,units,unit_price_eur,gross_eur\n")
            for r in result.rows:
                fh.write(
                    f"{r['store_id']},{r['sale_date']},{r['product_id']},{r['category']},"
                    f"{r['units']},{r['unit_price_eur']},{r['gross_eur']}\n"
                )
        return {
            "business_date": business_date,
            "row_count": len(result.rows),
            "clean_path": str(out),
        }

    # The one bit of SQL the orchestrator owns. Uses the pre-provisioned DW
    # connection, and is idempotent so a re-run is harmless.
    # NOTE: PostgresOperator is REMOVED in the Airflow 3 provider -- this is
    # SQLExecuteQueryOperator, and `database` replaced `schema`.
    ensure_warehouse_table = SQLExecuteQueryOperator(
        task_id="ensure_warehouse_table",
        conn_id=DW_CONN_ID,
        sql="""
        CREATE TABLE IF NOT EXISTS daily_revenue (
          business_date date          NOT NULL,
          store_id      text          NOT NULL,
          revenue_eur   numeric(14,2) NOT NULL,
          units_sold    integer       NOT NULL,
          loaded_at     timestamptz   NOT NULL DEFAULT now(),
          PRIMARY KEY (business_date, store_id)
        );
        """,
    )

    @task
    def load_warehouse(transformed: dict, **context) -> dict:
        """A3. Idempotent by contract: the loader replaces the date's rows.

        Worth noticing rather than writing: a plain INSERT here would silently
        double every figure on the second run, and nothing would look broken.
        """
        business_date = transformed["business_date"]
        cfg = team_config()

        # Reads what `transform` wrote. The data crossed on disk, not through
        # XCom -- and the aggregation is the same shared function the Dagster
        # half uses, so the two implementations differ only in orchestration.
        rows = revenue.rows_from_clean_csv(transformed["clean_path"], business_date)

        # The DSN comes from the Airflow CONNECTION, not from ROOTSMARKT_DSN.
        # Inside this container `localhost` is the container itself, so the env
        # var -- which is correct on the host for Dagster and roots -- points at
        # nothing here. It is also the same route `ensure_warehouse_table`
        # already takes: one answer to "where is the warehouse?", owned by the
        # orchestrator.
        written = load.load_daily_revenue(
            rows,
            business_date,
            dsn=load.dsn_from_airflow_conn(DW_CONN_ID),
            schema=cfg.schema,
        )
        return {"business_date": business_date, "rows_written": written}

    @task
    def validate_load(loaded: dict, **context) -> dict:
        """A3. A SEPARATE step, deliberately.

        If this lived inside `transform`, Airflow would only ever know "transform
        failed" -- not what was invalid. Keeping it separate is what makes the
        failure legible in the UI, and it is what keeps mission A4 possible.

        Scope is technical only: rows present, every store accounted for, no
        nulls, no negatives. It will pass on a EUR 0 day. That is not a bug.
        """
        cfg = team_config()
        report = validate.validate_load(
            loaded["business_date"],
            cfg.expected_stores,
            dsn=load.dsn_from_airflow_conn(DW_CONN_ID),
            schema=cfg.schema,
        )
        print(report)
        report.raise_for_status()
        return {
            "business_date": loaded["business_date"],
            "total_revenue_eur": float(report.total_revenue_eur),
            "store_count": report.store_count,
        }

    @task(outlets=[DAILY_REVENUE], retries=0)
    def publish_daily_revenue(validated: dict, **context) -> dict:
        """A4. The 07:00 incident.

        Every task above is green and the data product is worth nothing. Nobody
        has yet asked whether the number is *believable* -- so we do, and we make
        the pipeline stop when it is not.

        Two orchestration decisions live here:
          1. retries=0. A poisoned delivery is not a transient fault.
          2. The asset event is emitted ONLY on the success path, so anything
             scheduled on this asset is gated on valid data rather than a clock.

        Bounds come from the team's config, never a literal. `total > 0` would
        happily pass a EUR 12 day.
        """
        cfg = team_config()
        business_date = validated["business_date"]
        total = validated["total_revenue_eur"]

        if not cfg.is_plausible(total):
            raise AirflowFailException(
                f"implausible daily revenue for {business_date}: EUR {total:,.2f} "
                f"is outside {cfg.revenue_min_eur:,}-{cfg.revenue_max_eur:,}. "
                "Every upstream task succeeded. The data product is still wrong."
            )

        context["outlet_events"][DAILY_REVENUE].extra = {
            "business_date": business_date,
            "total_revenue_eur": total,
            "store_count": validated["store_count"],
            "plausible_range_eur": [cfg.revenue_min_eur, cfg.revenue_max_eur],
        }
        return {"business_date": business_date, "total_revenue_eur": total}

    delivery = fetch_delivery()
    current = assert_delivery_is_current(delivery)
    transformed = transform(current)
    loaded = load_warehouse(transformed)
    ensure_warehouse_table >> loaded
    publish_daily_revenue(validate_load(loaded))


rootsmarkt_delivery()
