# ---------------------------------------------------------------------------
# CHECKPOINT D3 -- generated by tools/build_checkpoints.py. Do not edit here.
#
# Everything up to and including mission D3 is solved. Everything after it is
# still the starter stub, waiting for you.
#
# Read it before you run it. Adopting a checkpoint is only worth the milestone
# you skipped if you understand what it does.
# ---------------------------------------------------------------------------
"""Rootsmarkt assets — missions D1 to D3.

This is your file for the Dagster block.

Same business problem as the Airflow half, asked the other way round. Airflow
asked "what work must run, in what order?" The question here is "what datasets
exist, what are they made of, and when is one valid?"

Read the briefs in `missions/`: D1, then D2, then D3.

WHAT IS ALREADY DONE FOR YOU
    - The project loads. `dg dev` will show you an empty asset graph right now.
    - All DATA PROCESSING is written and sealed in `rootsmarkt_processing`.
      The same modules your Airflow DAG used this morning.

WHAT YOU WILL WRITE
    Asset boundaries, dependency edges, metadata, and one check. Deciding what
    counts as a dataset is orchestration. Deciding what is worth attaching as
    metadata determines what this system can tell you in six months.

NO IO MANAGERS, NO RESOURCES
    These assets read and write directly and return `MaterializeResult`. That is
    a deliberate course decision, and it has one consequence you need up front:

        Because an asset returns MaterializeResult rather than a value, there is
        no stored output for a downstream asset to load. So you declare edges
        with `@asset(deps=[upstream])`, NOT by taking `upstream` as a function
        parameter. The parameter form is idiomatic Dagster when assets return
        values -- it just cannot work here.

STUCK?
    roots hint d1
    roots checkpoint d1
"""

# NOTE: deliberately NO `from __future__ import annotations` here.
# PEP 563 turns annotations into strings, and Dagster resolves the `context`
# parameter's type at runtime -- with the future import it fails with the
# confusing "Cannot annotate `context` parameter with type AssetExecutionContext.
# `context` must be annotated with AssetExecutionContext". Verified on 1.13.14.

import os
from pathlib import Path

from dagster import (
    AssetCheckResult,
    AssetCheckSeverity,
    AssetExecutionContext,
    MaterializeResult,
    MetadataValue,
    asset,
    asset_check,
)

from rootsmarkt_processing import clean, load, revenue, source
from rootsmarkt_processing.config import (
    clean_file,
    require_delivery_file,
    delivery_file,
    team_config,
)

# Partitions are out of scope for this course (master prompt section 18), so the
# business date is a plain setting rather than a partition key.
BUSINESS_DATE = os.environ.get("ROOTSMARKT_BUSINESS_DATE", "2026-03-04")

# NOTE: no module-level data paths. They come from
# rootsmarkt_processing.config, which anchors them to the repo root rather than
# the working directory -- `dg dev` runs steps with cwd=dagster/src, so a
# relative Path("data/raw") silently resolves to the wrong place and produces an
# empty glob instead of an error.


@asset(
    description="The delivery file as SupplyHub gave it to us. Unmodified.",
    kinds={"csv"},
)
def raw_delivery(context: AssetExecutionContext) -> MaterializeResult:
    cfg = team_config()
    client = source.SupplyHubClient(cfg.supplyhub_base_url, cfg.supplyhub_token, cfg.team_id)

    meta = client.get_delivery(BUSINESS_DATE)
    if meta.business_date != BUSINESS_DATE:
        # The A2 lesson, carried over: a 200 does not mean you got what you asked
        # for. Refusing to materialize is what keeps a stale file from becoming a
        # valid-looking asset.
        raise ValueError(
            f"asked SupplyHub for {BUSINESS_DATE} and was served {meta.business_date} "
            f"({meta.delivery_id}). Refusing to land a stale delivery as raw_delivery."
        )

    path = client.download(meta, delivery_file(meta.business_date))
    context.log.info("landed %s (%d rows)", meta.delivery_id, meta.row_count)

    return MaterializeResult(
        metadata={
            "delivery_id": meta.delivery_id,
            "business_date": meta.business_date,
            "row_count": meta.row_count,
            "store_count": meta.store_count,
            "checksum_sha256": MetadataValue.text(meta.checksum_sha256),
            "path": MetadataValue.path(str(path)),
        }
    )


@asset(
    deps=[raw_delivery],
    description="Typed, de-duplicated sales rows for the stores we actually run.",
    kinds={"csv"},
)
def clean_sales(context: AssetExecutionContext) -> MaterializeResult:
    cfg = team_config()
    result = clean.clean_sales(require_delivery_file(BUSINESS_DATE), cfg.expected_stores)

    # --- MISSION D3 FIX -------------------------------------------------------
    # SupplyHub includes its own test store in every delivery. It is real data in
    # the file, so no amount of type checking removes it -- deciding it does not
    # belong in Rootsmarkt's revenue is a business rule, and enforcing it is our
    # job, not the source's.
    #
    # This is the only line that changes in mission D3. Note what it means for
    # recovery: the file on disk did not change, so `raw_delivery` does not need
    # rebuilding. Only this asset and what depends on it do.
    expected = set(cfg.expected_stores)
    dropped = sorted({r["store_id"] for r in result.rows} - expected)
    rows = [r for r in result.rows if r["store_id"] in expected]
    # --------------------------------------------------------------------------

    out = clean_file(BUSINESS_DATE)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        fh.write("store_id,sale_date,product_id,category,units,unit_price_eur,gross_eur\n")
        for r in rows:
            fh.write(
                f"{r['store_id']},{r['sale_date']},{r['product_id']},{r['category']},"
                f"{r['units']},{r['unit_price_eur']},{r['gross_eur']}\n"
            )

    if dropped:
        context.log.info("excluded %d store(s) not on our roster: %s", len(dropped), dropped)

    return MaterializeResult(
        metadata={
            "row_count": len(rows),
            "store_count": len({r["store_id"] for r in rows}),
            "dropped_unexpected_stores": MetadataValue.text(", ".join(dropped) or "none"),
            "dropped_malformed": result.dropped_malformed,
            "dropped_duplicate": result.dropped_duplicate,
            "missing_expected_stores": MetadataValue.text(
                ", ".join(result.missing_expected_stores) or "none"
            ),
            "path": MetadataValue.path(str(out)),
        }
    )


@asset(
    deps=[clean_sales],
    description="Per-store daily revenue in the warehouse. What Finance reads at 07:00.",
    kinds={"postgres"},
)
def daily_revenue(context: AssetExecutionContext) -> MaterializeResult:
    cfg = team_config()

    # Read what clean_sales actually WROTE, rather than re-cleaning the raw file.
    # This matters beyond tidiness: re-deriving here would duplicate the D3
    # roster filter in two assets, so a participant fixing clean_sales alone
    # would see no change in revenue -- and mission D3's lesson would break.
    # Reading the upstream output also makes the dependency real rather than
    # merely declared.
    source_path = clean_file(BUSINESS_DATE)
    if not source_path.exists():
        raise FileNotFoundError(
            f"{source_path} is missing. Materialize clean_sales first."
        )

    rows = revenue.rows_from_clean_csv(source_path, BUSINESS_DATE)
    total = revenue.total_revenue_eur(rows)
    written = load.load_daily_revenue(rows, BUSINESS_DATE, schema=cfg.schema)

    context.log.info("loaded %d store rows totalling EUR %s", written, total)

    return MaterializeResult(
        metadata={
            "business_date": BUSINESS_DATE,
            "store_count": len(rows),
            "rows_written": written,
            # The number that made the 07:00 report wrong. Putting it on the
            # materialization is what let D1 see the incident before any check
            # had been written.
            "total_revenue_eur": MetadataValue.float(float(total)),
            "plausible_range_eur": MetadataValue.text(
                f"{cfg.revenue_min_eur:,} - {cfg.revenue_max_eur:,}"
            ),
        }
    )


@asset_check(
    asset=daily_revenue,
    blocking=True,
    description="Is this revenue figure believable for a grocery chain of our size?",
)
def revenue_is_plausible() -> AssetCheckResult:
    """Mission D2.

    The predicate is data processing. `blocking=True` is orchestration -- it is
    what stops an implausible figure from reaching anything downstream, and it is
    recorded against the asset rather than buried in a task log.

    Bounds come from the team's own config, never from a literal. A hardcoded
    `total > 0` would pass a EUR 12 day, which is exactly the trap A4 sets.
    """
    cfg = team_config()
    total = load.total_loaded_revenue(BUSINESS_DATE, schema=cfg.schema)
    passed = cfg.is_plausible(total)

    return AssetCheckResult(
        passed=passed,
        severity=AssetCheckSeverity.ERROR,
        description=(
            f"EUR {total:,.2f} for {BUSINESS_DATE}"
            + ("" if passed else f" is outside {cfg.revenue_min_eur:,}-{cfg.revenue_max_eur:,}")
        ),
        metadata={
            "total_revenue_eur": MetadataValue.float(float(total)),
            "min_eur": cfg.revenue_min_eur,
            "max_eur": cfg.revenue_max_eur,
            "business_date": BUSINESS_DATE,
        },
    )
